version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "9001:9000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py init_admin &&
            python manage.py runserver 0.0.0.0:9000"
    env_file:
      - .env
    depends_on:
      - db

  db:
      image: postgres:16.0-alpine3.17
      restart: always
      ports:
          - "5433:5432"
      env_file:
          - .env
      volumes:
          - my_db:$PGDATA

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A social_media_service worker -l info"
    depends_on:
      - app
      - redis
      - db
    restart: on-failure
    env_file:
      - .env